language: node_js # Programming language to install
node_js:
  - "14.15.1" # Version
cache: npm
dist: trusty # We will check dist?
sudo: required

branches: # Wich branch need travis execution
  only:
    - master # Branch to execute

before_script:
  - npm install -g @angular/cli # Command to execute before script

script:
  - ng lint
  - npm run test-headless
  - ng build --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/travis-ci
  on:
    branch: master
